### ISSUE TITLE
Can't add my LG TV anymore

### ISSUE THREAD

**Issue by Reemster** [athombv/com.lg.webos#10]
So the first time i add my LG television the app worked for 70%. Not all commands was working. Like the condition television is ON or OFF. And turning the television ON or OFF. And all the sudden the app did nothing anymore after a week and i tought if i re-install the app, maybe it's working again. BUT, i can't add the TV anymore. See pictures. 

I can ping the TV, so it's connected to my network (with WiFI)

![lg1](https://user-images.githubusercontent.com/19860405/32222380-5e32ac96-be39-11e7-95a5-3ec22150b186.jpg)
![lg2](https://user-images.githubusercontent.com/19860405/32222382-5e51a330-be39-11e7-84a8-6d19f198bff9.jpg)

**Comment by WeeJeWel** [comment]
This should be fixed in v2.0.2, now available as beta at https://apps.athom.com/app/com.lg.webos

**Comment by Reemster** [comment]
So the first issue is indeed fixt. But unfortunately the app can't still find my TV.
the only thing what i see now when i try to add my TV is an spinning gear. and after a few minutes
the message "invalid_session" 

And i can ping my television, and use the beta.

**Comment by WeeJeWel** [comment]
It should either show no devices or devices, not 'hang' inbetween.

Can you open the Chrome console and check for potential errors?

**Comment by Reemster** [comment]
did you mean this kind of errors?

Failed to load resource: the server responded with a status of 404 (Not Found)
/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/emit?_=1512416203982 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416213275 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416213275".
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416223280 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416223280".
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416233281 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416233281".
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416243281 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416243281".
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416253278 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416253278".
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 POST http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416263277 500 (Internal Server Error)
window.Homey.api @ api.js:1
heartbeatFn @ devices.js:1
api.js:1 XHR failed loading: POST "http://192.168.1.35/api/manager/drivers/pair/87e2b10731b6a92a4ba6de43384a17a9dda42e1c/heartbeat?_=1512416263277".

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2589

**Comment by Reemster** [comment]
Any update? still can't connect Homey with my LG TV.
