### ISSUE TITLE
LG OLED55C7V doesnt want to listen anymore

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/com.lg.webos#11]
Hi, 

for some reason our LG OLED55C7V stopped to listen a couple of days ago. When I try to reconnect the tv with homey I can see the message on my tv that Homey is connected but the commands that Homey sends are not understand. 

Could you please look into this?  The firmware version the TV is running on is 3.6

**Comment by WeeJeWel** [comment]
This should be fixed in v2.0.2, now available as beta at https://apps.athom.com/app/com.lg.webos
