### ISSUE TITLE
Volume slider in Device screen works (at first) but Flow action cards don't

### ISSUE THREAD

**Issue by bm480** [athombv/com.lg.webos#12]
I'm not sure if this is related to #3 or another issue but what I'm experiencing is that I'm able to pair the television, change the volume in the Device screen but any Flow action card for this device shows a red triangle (with a hint showing: not opnened) and nothing happens.

After a while (approx. 1 hr) the volume slider in the Device screen stopped working as well (you can change the slider but nothing happens). The TV has been on after pairing the whole time. I didn't have time at first to verify if the volume slider works in the Homey App, but when tried it also didn't work.

**Comment by WeeJeWel** [comment]
This should be fixed in v2.0.2, now available as beta at https://apps.athom.com/app/com.lg.webos
