### ISSUE TITLE
Is tv on or off?

### ISSUE THREAD

**Issue by addebc** [athombv/com.lg.webos#15]
It doesnt seem to know if tv is on or off...

The device is Always listed as ON in Homey GUI.  If i click in gui to switch it off it will change but as soon as i refresh it will be back ON again...

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2588

**Comment by fishfisher** [comment]
Is this issue being looked at? Please let me know if you need any logs or such - I will be happy to help.
