### ISSUE TITLE
LG Oled 55e6v - App can't find tv

### ISSUE THREAD

**Issue by Tim81** [athombv/com.lg.webos#16]
I've got a LG Oled 55e6v TV connected to the same wifi network but this Homey app tells me that it can't find the TV.

**Comment by Tim81** [comment]
It appears to be "fixed" after upgrading to firmware 05.30.30. This one is currently not offered automaticly, so needs to be done manually using USB firmware update method. The firmware version that was not working is 05.30.10, the previous and currently latest firmware that is offered automaticly.

**Comment by Sillec123** [comment]
I can find my tv but the pairing message doesn’t popup.

**Comment by darkytoothpaste** [comment]
i have the same problem with my 55C6T where there is no pairing message. i'm already on 5.30.30.

**Comment by WeeJeWel** [comment]
This is fixed in Homey v2.0.2, which will be released shortly!

**Comment by darkytoothpaste** [comment]
Is 2.0.2 released? I'm still in 2.0.0.

**Comment by ikelfkens** [comment]
According to my app it is released.
