### ISSUE TITLE
TV pairing still not working

### ISSUE THREAD

**Issue by ThaDuck** [athombv/com.lg.webos#17]
When I try to pair my LG TV (WebOS 2.0) the app recognizes my TV but the pairing message does not appear. I tried the same with an official LG app and that was working fine.

TV LG55UF776V
Homey v2.0.0
iOS App 2.0.2.246

**Comment by WeeJeWel** [comment]
This is solved with Homey v2.0.2, now available!

**Comment by ThaDuck** [comment]
Thanks for the update, I can confirm that it is working now. Thanks!
