### ISSUE TITLE
TV staying offline

### ISSUE THREAD

**Issue by rkokkelk** [athombv/com.lg.webos#3]
Hi,

SInce I have been using this app I have the following issue. When the app is installed and my TV is on, the app works correctly. However, when the app is installed (or homey is rebooted) and my TV is off it remains offline. Even though my I turn my TV on.

I've checked the source code and the initial `self.scanner.startScanning` detects my TV when it is on. However, the `self.scanner.startScanning` in `setInterval` does not detect my TV when it is initially turned off but later turned on. So there is an issue within the scanning function. 

But even if this works correctly it is still a strange implementation. Because if I start my TV in a flow I'll have to wait a maximum of 10 seconds before I can execute an action related to my TV. Also because I have entered the specifics of the TV I want to use, e.g. the IP and key, I do not need to scan for another TV in my network just to detect if my TV is turned on.

So I would like to propose the following, to include the `connectToDevice` function within every action and set it with a timeout of 1 or 2 seconds. So that every action will at first try to connect with the TV and then will execute the action. 

If you agree with this implementation please let me know because I have some spare time and some personal interest so that I can create a PR for you.

**Comment by WeeJeWel** [comment]
Yes, sounds good! Please go ahead and make a PR!

**Comment by JesperJanssen** [comment]
Same problem here with my LG OLED55E6. At first it works correctly (have set the TV to a fixed IP adres) but after a few days the TV appears to be offline according to Homey. Homey was not rebooted in the meantime and did not changed anything on the TV so for some kind of reason the App loses the connection with the TV or is not able to find it anymore. Too bad because I really like this kind of apps for Homey.

Homey firmware version = 1.2.2

**Comment by efriethoff** [comment]
Same problem here. I think I posted my issue in the wrong category, but can be read here:
https://github.com/athombv/homey/issues/1620

Every time I install the app, the flows will work, but as soon as I turn off the TV and on again, homey will report the TV offline. Everything on the TV is still the same, also same IP address.
I also have an app on my android cellphone to remote control the tv and that app connects with no problem.

My homey firmware = 1.3 rc12

**Comment by WeeJeWel** [comment]
Yep, it's a know issue and will be fixed soon :)

**Comment by efriethoff** [comment]
That would be awsome, thanks for the update

**Comment by rkokkelk** [comment]
For everyone interested and for who are willing to install an Homey app from source code, you can use my fix for this issue, see pull request #4. 

I've been using it for the last few weeks and works quite well, so I think it is an appropriate temprorary solution until the entire app is rewritten. Any suggestions or errors can be reported at the forked repository: [https://github.com/rkokkelk/com.lg.webos/tree/action_reconnect](https://github.com/rkokkelk/com.lg.webos/tree/action_reconnect).

**Comment by efriethoff** [comment]
Interested for sure, but I believe I need to use CLI to be able to install your fix and I don't feel comfortable in doing so. I guess I need to wait for the fix from Athom or something must come available. Thanks for your update, very much appreciated!!!

**Comment by efriethoff** [comment]
Is it possible to give an estimation how soon soon will be; please be more specific. It's already 4 weeks ago that you said it would be fixed soon, but please tell: "When?"

**Comment by WeeJeWel** [comment]
I usually don't give ETAs, but I hope to start with it next week :-)

**Comment by WeeJeWel** [comment]
I've (almost) finished the rewrite, it should be rock stable now.

The new App requires Homey v1.5.0 though, so depending on the update channel you're in, it will be available then.

**Comment by efriethoff** [comment]
Wow, that sounds great!! I am in the experimental channel, so i have to
wait a tiny bit longer. Thanks Emile!!!

Op 14 jul. 2017 12:20 p.m. schreef "Emile Nijssen" <notifications@github.com

**Comment by WeeJeWel** [comment]
I'm closing this issue as the new app has been out there already for some time. If the issue remains, please let me know.
