### ISSUE TITLE
Turn off TV using network

### ISSUE THREAD

**Issue by RobertMe** [athombv/com.lg.webos#5]
It is not possible to turn the TV off when the Homey is in another room. This because both power on and power off use IR to send these commands. But IMHO this app, which for 99% relies on the API, should use the API where possible. So I think it would be better if the power off was send using the API, and thus only power on would use IR and be dependent on the Homey and TV being "in IR range".

Note: if accepted I can also create a PR for this. But if there is some important reason to use IR in both cases I'm not gonna waste my time on creating the PR.

**Comment by WeeJeWel** [comment]
Yes, please create a PR that does both IR-off and Api-Off!

Emile

**Comment by RobertMe** [comment]
So you mean sending both the IR command as doing the API call at the same time? Couldn't that conflict? As I guess the IR for power on and power off will be the same, so then it would be possible that the TV is turned off by the API, and turned back on again by IR.

And IMO there is no point in sending the IR power off. As most of the interaction already uses the API, so sending the IR as fallback won't be needed as the rest of the app also doesn't work when the API is not available.

**Comment by WeeJeWel** [comment]
The power off command is discrete and not a toggle.

Sending both doesn't do any harm, yet it prevents a case where the TV
somehow isn't connected.
