### ISSUE TITLE
Allow manually adding a TV by IP

### ISSUE THREAD

**Issue by RobertMe** [athombv/com.lg.webos#6]
Currently adding the TV relies on it being available using the auto discovery. However when running a more complex network setup (firewall, multiple subnets, ...) the discovery might fail. So it would be nice if there was an option to manually enter the IP address of the TV.

I believe this is also dependent on some core changes, as as far as I know the device listing is a reusable view loaded from Homey core? So not something I could create a PR for (unless creating a whole new view which just looks like the core view).

**Comment by WeeJeWel** [comment]
Yes, this takes a lot of time to implement for a very few users, so it's not likely to ever happen. I suggest you to adjust your network configuration so discovery works.
