### ISSUE TITLE
Allow number input for volume in flow editor (instead of the slider)

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/com.lg.webos#7]
Could you change the slider for the volume input to a field in which the numerical value can be added? In this way it will be possible to create one flow with allows you to set the volume of the tv to every value between 0 -100 by using voice (or any other way). Now I have to create one flow for each volume level.

The slider for the volume is only convenient for the volume control with the Homey app and not in the flow editor.

Personally I would only use a field in which you can enter the numerical value instead of a slider for all devices in the flow editor. This would greatly improve the possibilities of Homey.

**Comment by WeeJeWel** [comment]
The slider also can receive a number token, have you tried that?

**Comment by JesperJanssen** [comment]
I did not knew that it was possible. Sorry for that. 

I figured out how to put a number token in the slider. I first needed to convert the variable from the IFTTT flow into a numerical variable (and then into a 0.xxx number) to get the slider to accept the variable. But now it works great in combination with my Google Home (_Hey Google set/turn/change tv volume to 20_)

**Comment by WeeJeWel** [comment]
Great!
