### ISSUE TITLE
Also allow number input for channel in flow editor 

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/com.lg.webos#9]
Now it is not possible to put a variable in the "set tv to channel" card in the flow editor. As a results you need to create a separate flow for each channel if you want to control them by voice.

One solution could be to add an extra card which allows us to just add a variable to the "set tv channel card" just like pressing the numbers on the remote of your tv.

**Comment by WeeJeWel** [comment]
This should be fixed in v2.0.2, now available as beta at https://apps.athom.com/app/com.lg.webos

I haven't been able to test the functionality yet because our office TV does not have any channels, so please let me know if it works!

**Comment by JesperJanssen** [comment]
I just tried it but when I put a number in the "set TV to channel number" card but this does not work. So adding a variable in that field will also not work.

Choosing a channel from the drop down list in the "Set TV to channel" card does work perfectly. Isn't there a way that you can use a number variable in this card and that it then automatically selects the channel which belongs to that number. Because when I enter a number in that card it gives me a choice from the drop down list. Or where you trying to do that with the other card (set TV to channel number)

**Comment by WeeJeWel** [comment]
Yeah, that was the intention. What didn't work? Did you get an error?

Emile Nijssen
Co-Founder & Creative Director

M emile@athom.nl <mailto:emile@athom.nl>
T +31640923136
W www.athom.com <https://www.athom.com/>

**Comment by JesperJanssen** [comment]
I did not get an error. When I put a 5 or 005 in the field it does not do anything when I test the flow

**Comment by WeeJeWel** [comment]
OK. I will test this in the upcoming days when I'm at home :)

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by JesperJanssen** [comment]
Works perfect now. Thanks!
